#version: '3'
services:
  streamlit_bedrock:
    build: 
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      - PROVIDER=bedrock
      - STREAMLIT_SERVER_PORT=8001
    depends_on:
      - mysql

  streamlit_openai:
    build: 
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - PROVIDER=openai
      - STREAMLIT_SERVER_PORT=8000
    depends_on:
      - mysql

  streamlit_gemini:
    build: 
      dockerfile: Dockerfile
    ports:
      - 8003:8003
    environment:
      - PROVIDER=gemini
      - STREAMLIT_SERVER_PORT=8003
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: