#version: '3'
services:
  streamlit_bedrock:
    container_name: streamlit_bedrock
    build: 
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      - PROVIDER=bedrock
      - STREAMLIT_SERVER_PORT=8001

  streamlit_openai:
    container_name: streamlit_openai
    build: 
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - PROVIDER=openai
      - STREAMLIT_SERVER_PORT=8000

  streamlit_gemini:
    container_name: streamlit_gemini
    build: 
      dockerfile: Dockerfile
    ports:
      - 8003:8003
    environment:
      - PROVIDER=gemini
      - STREAMLIT_SERVER_PORT=8003